import React from 'react';
import { PackageOpen, Trash2 } from 'lucide-react';
import { EmptyState, Badge, Pagination, Button } from '../../shared/ui';
import { formatCurrency, getCurrencySymbol } from '../../lib/currencies';
import type { PurchaseOrderFormTableProps } from './PurchaseOrderForm.types';

const ITEMS_PER_PAGE = 25;

export function PurchaseOrderFormTable({
  activeList,
  totalItemsNeeded,
  paginatedList,
  totalPages,
  currentPage,
  setCurrentPage,
  isAdmin,
  isGenerated,
  poMode,
  selectedSupplier,
  selectedCategory,
  estimatedCost,
  appSettings,
  updateItem,
  handleRemoveFromPO,
  removeFromManualList
}: PurchaseOrderFormTableProps) {
  return (
    <div className="bg-white dark:bg-surface rounded-md border border-neutral-200 dark:border-white/[0.08] overflow-hidden shadow-none flex flex-col min-h-[calc(100vh-340px)] justify-between print:border-none print:rounded-none">
      <div className="hidden print:block p-4 border-b border-black/20">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-xl font-bold uppercase mb-1">PURCHASE ORDER</h1>
            <p className="text-xs text-neutral-600">Supplier: <span className="font-semibold text-neutral-900">{selectedSupplier}</span></p>
            <p className="text-xs text-neutral-600">Category: <span className="font-semibold text-neutral-900">{selectedCategory}</span></p>
          </div>
          <div className="text-right">
            <p className="text-xs font-semibold">Date: {new Date().toLocaleDateString()}</p>
            <p className="text-[10px] text-neutral-500 mt-0.5">Generated by POS</p>
          </div>
        </div>
        <div className="mt-4 flex justify-between w-2/3 border-t border-black/10 pt-2 text-xs">
          <div>
            <p className="text-neutral-500 uppercase text-[10px]">Total Items Required</p>
            <p className="text-sm font-bold font-mono">{totalItemsNeeded.toLocaleString()}</p>
          </div>
          <div>
            <p className="text-neutral-500 uppercase text-[10px]">Est. Financial Need</p>
            <p className="text-sm font-bold font-mono">{formatCurrency(estimatedCost, appSettings.currency)}</p>
          </div>
        </div>
      </div>

      <div className="overflow-x-auto flex-1">
        {activeList.length === 0 ? (
          <EmptyState
            icon={<PackageOpen className="h-8 w-8 text-neutral-400" />}
            title={poMode === 'manual' ? "No items selected yet" : "Inventory is healthy"}
            subtext={poMode === 'manual'
              ? "Search products and add them to your purchase order"
              : "All items are currently above their defined reorder levels"}
            className="py-16"
          />
        ) : (
          <table className="w-full text-left border-collapse print:text-[10px]">
            <thead>
              <tr className="bg-neutral-50/50 dark:bg-white/[0.02] border-b border-neutral-200 dark:border-white/[0.08] h-8">
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500">Item / SKU</th>
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-center">Supplier</th>
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-center">Current</th>
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-center">Qty</th>
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-right">Cost ({getCurrencySymbol(appSettings.currency)})</th>
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-right">Retail ({getCurrencySymbol(appSettings.currency)})</th>
                <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-right">Total ({getCurrencySymbol(appSettings.currency)})</th>
                {isAdmin && <th className="px-3 text-[11px] font-medium uppercase text-neutral-500 text-right print:hidden">Ops</th>}
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-100 dark:divide-white/[0.04]">
              {paginatedList.map(item => (
                <tr key={item.id} className="h-11 hover:bg-neutral-50 dark:hover:bg-white/[0.02] transition-colors print:break-inside-avoid">
                  <td className="px-3">
                    <p className="font-medium text-neutral-900 dark:text-white text-[13px] leading-tight">{item.name}</p>
                    <p className="text-[11px] font-mono text-neutral-500 mt-0.5">{item.sku || 'No SKU'}</p>
                  </td>
                  <td className="px-3 text-center">
                    <input
                      type="text"
                      disabled={isGenerated}
                      value={item.supplier || ''}
                      onChange={(e) => updateItem(item.id, 'supplier', e.target.value)}
                      placeholder="Supplier"
                      className={`w-full max-w-[120px] h-7 px-2 bg-white dark:bg-app border border-neutral-200 dark:border-white/[0.08] text-center rounded text-[12px] text-neutral-900 dark:text-white focus:outline-none focus:border-primary ${isGenerated ? 'opacity-50 cursor-not-allowed' : ''}`}
                    />
                  </td>
                  <td className="px-3 text-center">
                    <span className={`px-2 py-0.5 rounded text-[11px] font-mono font-medium ${item.stock <= 0 ? 'bg-rose-500/10 text-rose-500' : 'bg-neutral-100 dark:bg-white/[0.06] text-neutral-700 dark:text-neutral-300'}`}>
                      {item.stock}
                    </span>
                  </td>
                  <td className="px-3 text-center">
                    <input
                      type="number"
                      value={item.neededQty}
                      onChange={(e) => updateItem(item.id, 'neededQty', Number(e.target.value))}
                      className="w-16 h-7 px-2 bg-white dark:bg-app border border-neutral-200 dark:border-white/[0.08] text-center rounded font-mono text-[12px] text-neutral-900 dark:text-white focus:outline-none focus:border-primary"
                    />
                  </td>
                  <td className="px-3 text-right">
                    <input
                      type="number"
                      value={item.cost}
                      onChange={(e) => updateItem(item.id, 'cost', Number(e.target.value))}
                      className="w-20 h-7 px-2 bg-white dark:bg-app border border-neutral-200 dark:border-white/[0.08] text-right rounded font-mono text-[12px] text-neutral-900 dark:text-white focus:outline-none focus:border-primary"
                    />
                  </td>
                  <td className="px-3 text-right">
                    <input
                      type="number"
                      value={item.price}
                      onChange={(e) => updateItem(item.id, 'price', Number(e.target.value))}
                      className="w-20 h-7 px-2 bg-white dark:bg-app border border-neutral-200 dark:border-white/[0.08] text-right rounded font-mono text-[12px] text-neutral-900 dark:text-white focus:outline-none focus:border-primary"
                    />
                  </td>
                  <td className="px-3 text-right text-[13px] font-mono tabular-nums font-semibold text-neutral-900 dark:text-white">
                    {formatCurrency(Number(item.neededQty || 0) * Number(item.cost || 0), appSettings.currency)}
                  </td>
                  {isAdmin && (
                    <td className="px-3 text-right print:hidden">
                      <Button
                        onClick={() => poMode === 'manual' ? removeFromManualList(item.id) : handleRemoveFromPO(item.id, item.name)}
                        variant="ghost"
                        size="sm"
                        className="h-7 w-7 !p-0 text-neutral-400 hover:text-rose-500"
                        title={poMode === 'manual' ? 'Remove from Selection' : 'Clear Target Level'}
                        icon={<Trash2 className="h-3.5 w-3.5" />}
                      />
                    </td>
                  )}
                </tr>
              ))}

              <tr className="font-semibold text-[13px] bg-neutral-50/50 dark:bg-white/[0.02] border-t border-neutral-200 dark:border-white/[0.08]">
                <td colSpan={6} className="text-right px-3 py-2 text-[11px] text-neutral-500 uppercase">Order Estimated Total:</td>
                <td className="text-right px-3 py-2 font-mono tabular-nums font-bold text-neutral-900 dark:text-white">{formatCurrency(estimatedCost, appSettings.currency)}</td>
                <td className="print:hidden"></td>
              </tr>
            </tbody>
          </table>
        )}
      </div>

      <div className="print-hide px-3 py-2 bg-neutral-50/50 dark:bg-white/[0.02] border-t border-neutral-200 dark:border-white/[0.08] flex items-center justify-between mt-auto">
        <p className="text-[11px] font-mono text-neutral-500">
          Showing {activeList.length === 0 ? '0 of 0 items' : `${((currentPage - 1) * ITEMS_PER_PAGE) + 1}–${Math.min(currentPage * ITEMS_PER_PAGE, activeList.length)} of ${activeList.length} items`}
        </p>
        <div className="flex items-center gap-1.5 ml-auto">
          <Pagination
            page={currentPage}
            totalPages={totalPages}
            totalItems={activeList.length}
            onPageChange={setCurrentPage}
            pageSize={ITEMS_PER_PAGE}
          />
        </div>
      </div>
    </div>
  );
}
