export function buildInitialFormData(appSettings: any) {
  return {
    storeName: appSettings?.storeName || '',
    storeAddress: appSettings?.storeAddress || '',
    storePhone: appSettings?.storePhone || '',
    storeEmail: appSettings?.storeEmail || '',
    storeWebsite: appSettings?.storeWebsite || '',
    storeLogo: appSettings?.storeLogo,
    taxRate: (appSettings?.taxRate || 0).toString(),
    currency: appSettings?.currency || 'PKR',
    receiptPrinter: appSettings?.receiptPrinter || false,
    autoBackup: appSettings?.autoBackup || false,
    invoicePrefix: appSettings?.invoicePrefix || 'INV',
    invoiceCounter: (appSettings?.invoiceCounter || 1000).toString(),
    invoicePadDigits: appSettings?.invoicePadDigits?.toString() || '4',
    receiptPaperSize: appSettings?.receiptPaperSize || '80mm',
    receiptDensity: appSettings?.receiptDensity || 'normal',
    receiptHeader: appSettings?.receiptHeader || '',
    receiptFooter: appSettings?.receiptFooter || '',
    receiptShowFooter: appSettings?.receiptShowFooter ?? true,
    receiptShowLogo: appSettings?.receiptShowLogo ?? true,
    receiptShowTax: appSettings?.receiptShowTax ?? true,
    receiptShowDiscount: appSettings?.receiptShowDiscount ?? true,
    receiptTemplate: appSettings.receiptTemplate || 'modern',
    receiptFontScale: appSettings.receiptFontScale?.toString() || '1',
    receiptFontBold: appSettings.receiptFontBold ?? false,
    receiptShowStoreName: appSettings.receiptShowStoreName ?? true,
    receiptShowStoreAddress: appSettings.receiptShowStoreAddress ?? true,
    receiptShowStorePhone: appSettings.receiptShowStorePhone ?? true,
    receiptShowStoreEmail: appSettings.receiptShowStoreEmail ?? true,
    receiptShowCustomerName: appSettings.receiptShowCustomerName ?? true,
    receiptShowCustomerPhone: appSettings.receiptShowCustomerPhone ?? true,
    receiptShowNotes: appSettings.receiptShowNotes ?? true,
    receiptShowBarcode: appSettings?.receiptShowBarcode ?? true,
    receiptShowDeliveryAddress: appSettings?.receiptShowDeliveryAddress ?? true,
    receiptShowQrCode: appSettings?.receiptShowQrCode ?? true,
    receiptPaddingTop: appSettings.receiptPaddingTop ?? 0,
    receiptPaddingBottom: appSettings.receiptPaddingBottom ?? 0,
    receiptPaddingLeft: appSettings.receiptPaddingLeft ?? 0,
    receiptPaddingRight: appSettings.receiptPaddingRight ?? 0,
    receiptOffsetX: appSettings.receiptOffsetX ?? 0,
    receiptHeaderOffsetX: appSettings.receiptHeaderOffsetX ?? 0,
    receiptFooterOffsetX: appSettings.receiptFooterOffsetX ?? 0,
    ai_v2_enabled: (appSettings as any).ai_v2_enabled ?? false,
    isLocked: (appSettings as any).isLocked ?? false,
    retailEnabled: (appSettings.retailEnabled ?? true) || !(appSettings.wholesaleEnabled ?? false),
    wholesaleEnabled: appSettings.wholesaleEnabled ?? false,
    touchKeyboardEnabled: appSettings.touchKeyboardEnabled ?? false,
    soundEnabled: appSettings.soundEnabled ?? true,
    enableKotPrinter: appSettings?.enableKotPrinter ?? false,
    autoSaveReceiptPng: appSettings?.autoSaveReceiptPng ?? false,
    taxId: appSettings?.taxId || '',
    country: appSettings?.country || 'PK',
    theme: (appSettings as any)?.theme || 'light',
    iconStyle: (appSettings as any)?.iconStyle || (typeof localStorage !== 'undefined' ? localStorage.getItem('pos_icon_style') : '3d') || '3d',
    interfaceMode: (appSettings as any)?.interfaceMode || 'touch',
    enableExtraCharges: appSettings?.enableExtraCharges ?? false,
    allowNegativeStock: appSettings?.allowNegativeStock ?? false,
    refundApprovalThreshold: appSettings?.refundApprovalThreshold ?? 5000,
    defaultSaleType: appSettings?.defaultSaleType || 'retail',
    barcodeBarWidth: appSettings?.barcodeBarWidth ?? 0.8
  };
}

export function syncFormDataFromSettings(appSettings: any) {
  return {
    storeName: appSettings?.storeName || '',
    storeAddress: appSettings?.storeAddress || '',
    storePhone: appSettings?.storePhone || '',
    storeEmail: appSettings?.storeEmail || '',
    storeWebsite: appSettings?.storeWebsite || '',
    storeLogo: appSettings?.storeLogo,
    taxRate: (appSettings?.taxRate || 0).toString(),
    currency: appSettings?.currency || 'PKR',
    receiptPrinter: !!appSettings?.receiptPrinter,
    autoBackup: !!appSettings?.autoBackup,
    invoicePrefix: appSettings?.invoicePrefix || 'INV',
    invoiceCounter: appSettings?.invoiceCounter?.toString() || '1000',
    invoicePadDigits: appSettings?.invoicePadDigits?.toString() || '4',
    receiptPaperSize: appSettings?.receiptPaperSize || '80mm',
    receiptDensity: appSettings?.receiptDensity || 'normal',
    receiptHeader: appSettings?.receiptHeader || '',
    receiptFooter: appSettings?.receiptFooter || '',
    receiptShowFooter: appSettings?.receiptShowFooter ?? true,
    receiptShowLogo: appSettings?.receiptShowLogo ?? true,
    receiptShowTax: appSettings?.receiptShowTax ?? true,
    receiptShowDiscount: appSettings?.receiptShowDiscount ?? true,
    receiptTemplate: appSettings?.receiptTemplate || 'modern',
    receiptFontScale: appSettings?.receiptFontScale?.toString() || '1',
    receiptFontBold: !!appSettings?.receiptFontBold,
    receiptShowStoreName: appSettings?.receiptShowStoreName ?? true,
    receiptShowStoreAddress: appSettings?.receiptShowStoreAddress ?? true,
    receiptShowStorePhone: appSettings?.receiptShowStorePhone ?? true,
    receiptShowStoreEmail: appSettings?.receiptShowStoreEmail ?? true,
    receiptShowCustomerName: appSettings?.receiptShowCustomerName ?? true,
    receiptShowCustomerPhone: appSettings?.receiptShowCustomerPhone ?? true,
    receiptShowNotes: appSettings?.receiptShowNotes ?? true,
    receiptShowBarcode: appSettings?.receiptShowBarcode ?? true,
    receiptShowDeliveryAddress: appSettings?.receiptShowDeliveryAddress ?? true,
    receiptShowQrCode: appSettings?.receiptShowQrCode ?? true,
    receiptPaddingTop: appSettings?.receiptPaddingTop ?? 0,
    receiptPaddingBottom: appSettings?.receiptPaddingBottom ?? 0,
    receiptPaddingLeft: appSettings?.receiptPaddingLeft ?? 0,
    receiptPaddingRight: appSettings?.receiptPaddingRight ?? 0,
    receiptOffsetX: appSettings?.receiptOffsetX ?? 0,
    receiptHeaderOffsetX: appSettings?.receiptHeaderOffsetX ?? 0,
    receiptFooterOffsetX: appSettings?.receiptFooterOffsetX ?? 0,
    ai_v2_enabled: !!(appSettings as any)?.ai_v2_enabled,
    isLocked: !!(appSettings as any)?.isLocked,
    retailEnabled: !!appSettings?.retailEnabled || !appSettings?.wholesaleEnabled,
    wholesaleEnabled: !!appSettings?.wholesaleEnabled,
    touchKeyboardEnabled: !!appSettings?.touchKeyboardEnabled,
    soundEnabled: !!appSettings?.soundEnabled,
    enableKotPrinter: !!appSettings?.enableKotPrinter,
    autoSaveReceiptPng: !!appSettings?.autoSaveReceiptPng,
    taxId: appSettings?.taxId || '',
    country: appSettings?.country || 'PK',
    theme: (appSettings as any)?.theme || 'light',
    iconStyle: (appSettings as any)?.iconStyle || (typeof localStorage !== 'undefined' ? localStorage.getItem('pos_icon_style') : '3d') || '3d',
    interfaceMode: (appSettings as any)?.interfaceMode || 'touch',
    enableSplitPayment: appSettings?.enableSplitPayment ?? false,
    enableExtraCharges: appSettings?.enableExtraCharges ?? false,
    allowNegativeStock: appSettings?.allowNegativeStock ?? false,
    refundApprovalThreshold: appSettings?.refundApprovalThreshold ?? 5000,
    defaultSaleType: appSettings?.defaultSaleType || 'retail',
    barcodeBarWidth: appSettings?.barcodeBarWidth ?? 0.8
  };
}
